### ISSUE TITLE
Globals do not resolved when run on Node v. 10

### ISSUE THREAD

**Issue by purumpum** [SimenB/jest-environment-jsdom-sixteen#2]
I experienced following errors when run my tests on Node v. 10.13.0: `ReferenceError: window is not defined` and `ReferenceError: describe is not defined`. It is the same errors as for `jest-environment-node` described in https://github.com/facebook/jest/issues/9453, but I think it is worth to mention this issue here.

This behavior introduced with implementation of `getVmContext()` method and does not affect `jest-environment-jsdom`. It it caused by a bug in old versions of Node https://github.com/nodejs/node/pull/23206 and fixed in Node v. 10.14.2.

**Comment by SimenB** [comment]
Sorry, somehow missed this issue... "Fixed" by specifying a fixed node version in the `engines` field
