### ISSUE TITLE
Unable to use package with testEnvironment in jest config

### ISSUE THREAD

**Issue by ImmanuelSegol** [SimenB/jest-environment-jsdom-sixteen#4]
Hi,
Im using your package to fix the issue described here:
https://github.com/testing-library/dom-testing-library/releases/tag/v7.0.0

If I use the library like this all is grate"
`"test": "react-scripts test --env=jest-environment-jsdom-sixteen"`

How ever when trying to include it in the jest config as so:
```
"jest": {
    "testEnvironment": "jest-environment-jsdom-sixteen"
  },

```

I see no effect as if the `testEnvironment` is ignored.

And I get the same error as described in the link to the dom-testing-library release.

Thanks :)

**Comment by tim-phillips** [comment]
You might need to add `react-scripts test -- --config jest.config.js` to do it that way. 

https://stackoverflow.com/a/61468737/1386245

**Comment by SimenB** [comment]
Issue with `react-scripts` I think
