### ISSUE TITLE
Support NodeJS 11

### ISSUE THREAD

**Issue by leonardovillela** [SimenB/jest-environment-jsdom-sixteen#5]
HI @SimenB,

I was trying to start using this package and I see the NodeJS version 11 is not supported on engines, any specific reason for this?

![image](https://user-images.githubusercontent.com/8650543/84141647-68752c00-aa4b-11ea-87db-b78b5200abc8.png)

**Comment by SimenB** [comment]
11 has been EOL since June 2019

https://github.com/nodejs/Release/blob/master/README.md#end-of-life-releases
