### ISSUE TITLE
Support Jest26

### ISSUE THREAD

**Issue by santiph** [SimenB/jest-environment-jsdom-sixteen#8]
My project needs jest26 to run, but with the latest version of `jest-environment-jsdom-sixteen` it has multiple versions of jest packages installed:
```
├─ jest-environment-jsdom-sixteen@1.0.3
│  ├─ @jest/console@25.3.0
│  ├─ @jest/fake-timers@25.1.0
│  ├─ @jest/source-map@25.2.6
│  ├─ @jest/test-result@25.3.0
│  ├─ @jest/types@25.5.0
│  ├─ jest-message-util@25.1.0
│  ├─ jest-mock@25.1.0
│  └─ jest-util@25.3.0
```

Since JSDOM 16 is already shipped with Jest, is there any reason to keep this library, or could it be removed?

It'd be great to get them all aligned 🙏

**Comment by Smrtnyk** [comment]
I have issue where I use this lib in jest 26 but it uses lolex timers if I want to use modern timers so it throws an error

If I use jsdom that ships with jest 26 then for some reason my window.performance is undefined

**Comment by SimenB** [comment]
03837baa9afc9dce0bdbf8c711401571646a723f
